### ISSUE TITLE
Error while creating new riba project

### ISSUE THREAD

**Issue by SPKorhonen** [ribajs/riba#37]
While generating a new riba project I encountered the following error:

UPDATE riba-test/src/ts/binders/index.ts (68 bytes)
SyntaxError: Unexpected identifier
    at Function (<anonymous>)
    at Object.template (/home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/@angular-devkit/core/src/utils/template.js:258:16)
    at /home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/@angular-devkit/schematics/src/rules/template.js:36:45
    at /home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/@angular-devkit/schematics/src/rules/base.js:110:30
    at /home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:229:13
    at /home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:42:59
    at Array.forEach (<anonymous>)
    at HostDirEntry.visit (/home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:42:43)
    at FilterHostTree.visit (/home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:228:19)
    at /home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/@angular-devkit/schematics/src/rules/base.js:106:14

Failed to execute command: "/home/ctbuild/.nvm/versions/node/v18.16.0/lib/node_modules/@ribajs/cli/node_modules/.bin/schematics" @ribajs/schematics:formatter --name=riba-test-example --project="riba-test" --path=riba-test/src/ts/formatters --no-dry-run --no-skip-git --no-skip-examples --no-skip-install --package-manager="npm" --language="ts" --styleLanguage="scss" --templateEngine="html" --collection="@ribajs/schematics" --sourceRoot="src/ts" --flat
▹▹▹▹▹ Installation in progress... ☕

**Comment by JumpLink** [comment]
Hello @SPKorhonen,

Thank you for bringing this to our attention. I apologize for the inconvenience. Currently, I'm in the process of rewriting the CLI, and I admit it hasn't been given the priority it deserves recently.

For a quick workaround, I'd recommend using one of our demos as a starting point. Specifically, you can refer to the [bs5-slider demo](https://github.com/ribajs/riba/tree/main/demos/bs5-slider) since this uses Vite instead of Webpack, which I would like to switch to in the long term. When using this demo, please ensure you update the version of the dependencies. Change the version from workspace:^ to either latest or 2.0.0-rc.5.

I hope this helps! Let me know if you have any further questions or concerns.
