### ISSUE TITLE
Riba CLI scaffold error

### ISSUE THREAD

**Issue by hanc2006** [ribajs/riba#4]
Hi,
I wanted to start using this library but I have some problems with the initial setup of the project. 
This is the command output:

**Command:**
$: npm i -g @ribajs/cli
$: riba new website

**Output:**
`TypeError: program.version is not a function
    at bootstrap (/home/hanc/.npm-global/lib/node_modules/@ribajs/cli/src/bin/riba.ts:13:11)
    at Object.<anonymous> (/home/hanc/.npm-global/lib/node_modules/@ribajs/cli/src/bin/riba.ts:22:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)`

**System information:**
npm: '6.12.0',
  ares: '1.15.0',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.2',
  modules: '64',
  napi: '3',
  nghttp2: '1.37.0',
  node: '10.15.2',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '11.0',
  uv: '1.30.1',
  v8: '6.8.275.32-node.12',
  zlib: '1.2.11'
 OS: Linux x64 5.3.0-11.2-liquorix-amd64

**Comment by hanc2006** [comment]
I resolved importing the required module directly instead **__importStart()**. It's a temporary change but at least it works:

![image2](https://i.imgur.com/KtvQr1I.png)

**Comment by JumpLink** [comment]
Thank you for your issue, I have just released a new version (1.7.0) which should fix the problem, could you check it?
